/**
 * this file was auto-generated by AliceLex
 * https://github.com/YuhangGe/alicelex
 * https://github.com/YuhangGe/Jing
 */
var $ = require('./util.js');
var BaseRender = require('./base_render.js');

var GLOBAL______DEFAULT = 15, GLOBAL______COMMENT = 16, GLOBAL______VAR = 17, IF______DEFAULT = 18;


    var CON_STR = '';


var SilenceRender = function() {
    this.base();
    this.START_ACTION = 15;
    /*
    this.ig = true;
    */
    var _i = Int32Array ? Int32Array : Array;

    this.TABLE = {
    	_base : new _i(19),
    	_default : new _i(19),
    	_check : new _i(41),
    	_next : new _i(41),
    	_action : new _i(19),
    	_eqc : new _i(256)
    };

    this._str_to_arr(["\0\1\1\1\1\1\1\1\1\2\1\4\7\16\25\34\1\43\6\7", "\1\13\0\2\11\2\10\4\0\2\15\2\0\2\16\2\17", "\1\3\0\2\20\2\12\2\10\2\11\2\13\2\14\2\22\2\23\2\0\3\14\3\15\2\0\5\15\4\16\2\0\4\16\4\17\2\0\4\17\10\21","\0\0\0\14\4\10\13\1\3\6\7\0\11\2\15\15\0\15\15\15\15\16\16\16\0\16\16\16\17\17\17\0\17\17\17\5\12\5\5\5\5\5", "\0\5\6\1\2\3\10\15\4\0\3\0\13\12\7\14\0\0\0\0", "\1\45\1\2\7\6\1\2\2\5\1\2\6\22\1\33\5\5\1\2\5\2\1\33\5\2\3\2\1\2\4\x83\1"], [this.TABLE._base, this.TABLE._default, this.TABLE._check, this.TABLE._next, this.TABLE._action, this.TABLE._eqc]);

    

};
SilenceRender.prototype = {
    action : function(action) {
        switch(action) {
            case 4:

    var _f = this.yytext();
    $.log("end func: "+_f);

break;
case 5:

	this.yygoto(GLOBAL______VAR);	

break;
case 3:

	var _f = this.yytext();
	$.log("func: "+_f);
	switch(_f) {
		case '{if':
			this.yygoto(IF______DEFAULT);
			break;
	  //  case '{for':
	    //	this.yygoto(FOR______DEFAULT);
	    //	break;
	    default:
	    	throw 'unknow render function.';
	    	console.trace();
	    	break;
	}

break;
case 0:

    this.cmt_idx = this.yyidx;
	this.yygoto(GLOBAL______COMMENT);

break;
case 10:

    //do nothing
    $.log("other: " + this.yytext());

break;
case 9:

    $.log("cnt: " + this.yytext());

break;
case 1:

    $.log("cmt: "+this.yysrc.substring(this.cmt_idx, this.yyidx + this.yylen));
    this.yygoto(GLOBAL______DEFAULT);

break;
case 2:

    //do nothing

break;
case 7:

	//ignore space.

break;
case 6:

	$.log('var: ' + this.yytext());

break;
case 12:

    this.yygoto(GLOBAL______DEFAULT);

break;
case 11:

    $.log("if con: " + this.yytext());

break;

            default :
                break;
        }
    }
};
$.inherit(, BaseRender);



(function() {
    var lexer = new SilenceRender();
    var cnt = $.readFile($.parseFileName('./test.tpl'));
    lexer.lex(cnt);
})();


